create table if not exists public.vision_training_samples (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    analysis_id text not null,
    target_type text not null check (target_type in ('agent', 'skill')),
    event_index integer not null default -1,
    label text not null,
    predicted_label text not null default '',
    feature jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, analysis_id, target_type, event_index)
);

create index if not exists vision_training_samples_target_idx
    on public.vision_training_samples (target_type, label);

create table if not exists public.vision_model_centroids (
    target_type text not null check (target_type in ('agent', 'skill')),
    label text not null,
    sample_count integer not null default 0,
    centroid jsonb not null,
    updated_at timestamptz not null default now(),
    primary key (target_type, label)
);

alter table public.vision_training_samples enable row level security;
alter table public.vision_model_centroids enable row level security;

revoke all on table public.vision_training_samples from anon, authenticated;
revoke all on table public.vision_model_centroids from anon, authenticated;

grant all on table public.vision_training_samples to service_role;
grant all on table public.vision_model_centroids to service_role;

grant usage, select on sequence public.vision_training_samples_id_seq to service_role;

comment on table public.vision_training_samples is
'Feature vectors extracted from user-corrected VALORANT frames. Raw images are not stored.';

comment on table public.vision_model_centroids is
'Online supervised classifier weights learned from corrected agent/skill feature vectors.';
